// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDY0f_ONGZ0FWcZaM0eEOssmOsooilfSl0',
    appId: '1:708297621387:web:e035b2138f53b35226f98e',
    messagingSenderId: '708297621387',
    projectId: 'basic-crud-2f78a',
    authDomain: 'basic-crud-2f78a.firebaseapp.com',
    storageBucket: 'basic-crud-2f78a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtJHUxyfWgAVTC0l3Qo1pfN6dgjKsk36Y',
    appId: '1:708297621387:android:74f357398591af2826f98e',
    messagingSenderId: '708297621387',
    projectId: 'basic-crud-2f78a',
    storageBucket: 'basic-crud-2f78a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANEF45pZFvbOakSlF4J582CN9SjPFToxM',
    appId: '1:708297621387:ios:b6d9fe77a4452d5d26f98e',
    messagingSenderId: '708297621387',
    projectId: 'basic-crud-2f78a',
    storageBucket: 'basic-crud-2f78a.firebasestorage.app',
    iosBundleId: 'com.example.musicPlayerV1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANEF45pZFvbOakSlF4J582CN9SjPFToxM',
    appId: '1:708297621387:ios:b6d9fe77a4452d5d26f98e',
    messagingSenderId: '708297621387',
    projectId: 'basic-crud-2f78a',
    storageBucket: 'basic-crud-2f78a.firebasestorage.app',
    iosBundleId: 'com.example.musicPlayerV1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDY0f_ONGZ0FWcZaM0eEOssmOsooilfSl0',
    appId: '1:708297621387:web:9ee22ebbff81584626f98e',
    messagingSenderId: '708297621387',
    projectId: 'basic-crud-2f78a',
    authDomain: 'basic-crud-2f78a.firebaseapp.com',
    storageBucket: 'basic-crud-2f78a.firebasestorage.app',
  );
}
